/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        fin: {
          bg: 'var(--fin-bg)',
          surface: 'var(--fin-surface)',
          'surface-2': 'var(--fin-surface-2)',
          border: 'var(--fin-border)',
          'text-primary': 'var(--fin-text-primary)',
          'text-secondary': 'var(--fin-text-secondary)',
          'text-muted': 'var(--fin-text-muted)',
          brand: 'var(--fin-brand)',
          'brand-soft': 'var(--fin-brand-soft)',
          'brand-hover': 'var(--fin-brand-hover)',
          'brand-active': 'var(--fin-brand-active)',
          positive: 'var(--fin-positive)',
          'positive-soft': 'var(--fin-positive-soft)',
          'positive-hover': 'var(--fin-positive-hover)',
          'positive-active': 'var(--fin-positive-active)',
          negative: 'var(--fin-negative)',
          'negative-soft': 'var(--fin-negative-soft)',
          'negative-hover': 'var(--fin-negative-hover)',
          'negative-active': 'var(--fin-negative-active)',
          warning: 'var(--fin-warning)',
          'warning-soft': 'var(--fin-warning-soft)',
          'warning-hover': 'var(--fin-warning-hover)',
          'warning-active': 'var(--fin-warning-active)',
          invest: 'var(--fin-invest)',
          'invest-soft': 'var(--fin-invest-soft)',
          'invest-hover': 'var(--fin-invest-hover)',
          'invest-active': 'var(--fin-invest-active)',
          'ghost-hover': 'var(--fin-ghost-hover)',
          'ghost-active': 'var(--fin-ghost-active)',
          'highlight-row': 'var(--fin-highlight-row)',
          'highlight-selected': 'var(--fin-highlight-selected)',
          overlay: 'var(--fin-overlay)',
          'disabled-bg': 'var(--fin-disabled-bg)',
          'disabled-text': 'var(--fin-disabled-text)',
        },
      },
      boxShadow: {
        'fin-focus': '0 0 0 3px var(--fin-focus-ring)',
      },
      fontFamily: {
        fin: ['Inter', 'system-ui', 'sans-serif'],
        'fin-mono': ['DM Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
